### ISSUE TITLE
Not works with magento commerce having b2b features enabled.

### ISSUE THREAD

**Issue by emirajbbd** [saleslayer/magento-enterprise-plugin#5]
![2023-03-08_0359](https://user-images.githubusercontent.com/63784/223563517-c9c265f1-7e7f-40ef-8149-c5ddf2403a1f.png)
then I found
![2023-03-08_0340](https://user-images.githubusercontent.com/63784/223562810-6b67a8ae-2eee-4957-b2e8-a85f5c2a53d6.png)
Then I updated codes so that the sync works

![2023-03-08_0353](https://user-images.githubusercontent.com/63784/223563674-68b47dbb-2a45-4d61-895f-e15d098d9471.png)

**Comment by moreno24** [comment]
Hi Enamul,

We'll analyze this issue and have it into account for the next update.

Thank you very much for the information, very appreciated.
